package org.xiaowu.behappy.koa.ratelimit;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class BehappyKoaRatelimitDashboardApplication  {

    public static void main(String[] args) {
        SpringApplication.run(BehappyKoaRatelimitDashboardApplication.class, args);
    }
}
